version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      RAILS_ENV: development
      SECRET_KEY_BASE: bd006e747a8397942e34ab5650ac07dec77bb8df74df819296e66607c5f46e5be893bebc9e2b86895a3663c3581d488db64938f4a1f8d7a981953a1ec0975b02
      DATABASE_URL: postgres://postgres:password@db:5432/rails_dev

volumes:
  db_data:
